FROM apache/airflow:3.3.1

# Copy Python dependencies
COPY requirements.txt /requirements.txt

# Install project dependencies
RUN pip install --no-cache-dir \
    "apache-airflow==${AIRFLOW_VERSION}" \
    -r /requirements.txt